### ISSUE TITLE
Layout issues with signup example

### ISSUE THREAD

**Issue by MartinSStewart** [funk-team/funkLang#37]
The signup example here https://sign-up.builtwithfunk.com/ doesn't line break the subtitle text causing it to quickly appear under the signup card. Additionally there's no spacing in part of the terms of service text. 

![image](https://user-images.githubusercontent.com/5068391/112670587-64db5600-8e61-11eb-9eb9-3dad391d27ba.png)

**Comment by davidjb99** [comment]
Thanks Martin, this did actually work when the login example was created, we re-factored the text interaction and I guess introduced a bug. We will write an e2e test for this.

**Comment by davidjb99** [comment]
This is fixed we just need to update the examples @andressotomayorb

**Comment by FranzSkuffka** [comment]
https://sign-up.builtwithfunk.com/ is working.

**Comment by MartinSStewart** [comment]
It looks like this on my screen which I'm guessing isn't correct? I'm using Firefox and Windows 10. 

![image](https://user-images.githubusercontent.com/5068391/112729675-b9e49e00-8f2d-11eb-8830-ae0e1ceb75ef.png)

**Comment by davidjb99** [comment]
> It looks like this on my screen which I'm guessing isn't correct? I'm using Firefox and Windows 10.
> 

Try refreshing the page :)

**Comment by MartinSStewart** [comment]
Oops, yes it was just a caching issue. Looks good now!
