### ISSUE TITLE
Error during service worker registration

### ISSUE THREAD

**Issue by sporto** [funk-team/funkLang#39]
Hi 
When trying to open the editor I see this

![image](https://user-images.githubusercontent.com/1005498/112714620-39bf3800-8f2f-11eb-9b63-f5e98c6da35b.png)

This is Chrome 88 on MacOS

Thanks

**Comment by FranzSkuffka** [comment]
Thanks for trying out funk and reporting this issue.

I just installed chrome 89 for testing this and can not reproduce the error. Can you confirm the problem persists after reloading the page and in anonymous mode?

**Comment by sporto** [comment]
It loads fine in Incognito, same error otherwise

**Comment by FranzSkuffka** [comment]
Sounds like it could be a browser extension. Do you use many plugins?

**Comment by sporto** [comment]
Ok, will try disabling them

**Comment by sporto** [comment]
I appears that was the case.

I disabled all the extensions and restarted Chrome, the editor loaded fine.
Then I started enabling extensions, but the editor kept working all the way.
So it seeems an extension was the issue somehow, but I cannot tell which one.
