### ISSUE TITLE
I Would like to contrinute

### ISSUE THREAD

**Issue by afidegnum** [funk-team/funkLang#58]
Hi, 
I have been building something similar, due to lack of resources 3 years ago, I have resorted to elisp. but I would love to assist in making this project a success.

What are the available roadmaps?

**Comment by FranzSkuffka** [comment]
Hey thank you so much!

we are currently evaluating new technology as well as information and requirements from a potential pilot partner so it's not entirely clear yet. I woke love to have a chat though to learn more about your similar project and your interests.

**Comment by afidegnum** [comment]
OK, I sent you a mail
